services:
  db:
    image: postgres:17.0
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data-test:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db-data-test:
