name: Continuous Delivery

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Continuous Integration" ]
    types: [ "completed" ]
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Publish
      run: dotnet publish ./src/Numerous.Web/Numerous.Web.csproj -c Release --os linux -o ./dist
    - name: Deploy
      run: >
        echo "Restarting service $SERVICE_NAME..." &&
        systemctl stop $SERVICE_NAME &&
        echo "Moving files to $DEPLOYMENT_PATH..." &&
        mv -f ./dist/* $DEPLOYMENT_PATH &&
        systemctl start $SERVICE_NAME
