name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Inspect Code
      run: >
        dotnet tool install -g JetBrains.ReSharper.GlobalTools &&
        jb inspectcode --no-build --swea --output="inspectcodereport.xml" --verbosity=WARN -f="xml" "Numerous.sln"
    - name: Inspection Report
      run: >
        dotnet tool install -g nvika && 
        nvika parsereport "inspectcodereport.xml" --treatwarningsaserrors
    - name: Test
      run: dotnet test --no-build --verbosity normal
