name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  inspect:
    name: Build and Inspect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: .NET Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0
      - name: .NET Build
        shell: bash
        run: dotnet build
      - name: JetBrains Inspect Code
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools && jb inspectcode --no-build --verbosity=TRACE --swea --output=inspectcode.xml Numerous.sln
      - name: Inspection Report
        run: dotnet tool install -g nvika && nvika parsereport "${{ github.workspace }}/inspectcode.xml" --debug --treatwarningsaserrors
