name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ vars.USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      run: docker buildx build -t ghcr.io/pasi4k5/numerous:latest --platform linux/amd64,linux/arm64 --push .
